### ISSUE TITLE
insuficcient documentation for the entire process of spin-up

### ISSUE THREAD

**Issue by droopy4096** [StackStorm/st2-dockerfiles#14]
I have attempted spinning up the st2 cluster, however it is not apparent how do I get to a point of running "st2" commands. Some of the steps outlined seem to be taking from "half-way in" etc. 

Can somebody carefully walk through the README and update it with current procedure for loading and running produced docker images?

**Comment by armab** [comment]
Updated [README](https://github.com/StackStorm/st2-dockerfiles#build-your-own-stackstorm-docker-images) via https://github.com/StackStorm/st2-dockerfiles/pull/30 in
