### ISSUE TITLE
St2Mistral Dockerfile

### ISSUE THREAD

**Issue by toninis** [StackStorm/st2-dockerfiles#18]
Is there a way to enable Mistral on this stack ?

**Comment by toninis** [comment]
Thanks for your prompt answer @armab .

**Comment by armab** [comment]
Closing, as Dockerfiles rely on `Ubuntu Bionic` are shipped with no mistral.
Additionally, st2mistral is in process to be deprecated within the st2 `v3.3.0` roadmap.
