### ISSUE TITLE
Current build procces looks broken

### ISSUE THREAD

**Issue by freeseacher** [StackStorm/st2-dockerfiles#29]
We have images with debian but packages for  ubuntu/trusty. 
and the final

```
dpkg: dependency problems prevent configuration of st2:
 st2 depends on libc6 (>= 2.15); however:
  Version of libc6:amd64 on system is 2.13-38+deb7u11.
 st2 depends on libffi6 (>= 3.0.4); however:
  Package libffi6 is not installed.
```

Please finish migration to ubuntu or revert changes to debian. 
tnx

**Comment by armab** [comment]
You can't install `ubuntu trusty` packages under `debian wheezy`, of course.

Debian packages are available under the `staging` repositories, see: 
https://packagecloud.io/stackstorm/staging-stable

Take a look at working build instructions here: https://github.com/StackStorm/st2-dockerfiles/issues/21#issuecomment-238953031
