### ISSUE TITLE
st2web may fail to resolve upstream hosts on IP changes

### ISSUE THREAD

**Issue by winem** [StackStorm/st2-dockerfiles#29]
I noticed and issue with the nginx proxy configuration while running some more tests related to https://github.com/StackStorm/st2-dockerfiles/pull/28 (see https://github.com/StackStorm/st2-dockerfiles/pull/28#issuecomment-626248413)

The issue is caused by the fact that nginx resolves the upstream hosts during the startup and caches the response until the next restart. This leads to issues if any of the upstream hosts gets a new IP address due to a restart for example. 

I will create a PR to address this issue.

**Comment by armab** [comment]
Turns out creating an issue was too early here as the problem was related to WIP `docker-compose` https://github.com/StackStorm/st2-dockerfiles/pull/28#discussion_r422671119 which is not merged yet.

**Comment by winem** [comment]
I will do a bit more research on this topic. 

I created the issue because this may happen in any environment running the st2web container. 

Discussion in the community slack for a few more details: https://stackstorm-community.slack.com/archives/CCCNZUGUA/p1589111953039600

I will set the PR to draft for now and will keep this issue open until we know how to fix this for all kind of deployments.

**Comment by winem** [comment]
A solution is under development and will be part of https://github.com/StackStorm/st2-dockerfiles/pull/28

**Comment by armab** [comment]
Closed via https://github.com/StackStorm/st2-dockerfiles/pull/28
