### ISSUE TITLE
Remove openssh server keys from st2 docker images

### ISSUE THREAD

**Issue by ashm2** [StackStorm/st2-dockerfiles#36]
We noticed openssh keys on few st2 docker containers which is causing security vulnerabilities when scanned.

```
# docker run -it stackstorm/st2stream:3.3dev bash
--
Welcome to StackStorm HA v3.3dev (Ubuntu 18.04.4 LTS GNU/Linux x86_64)
* Documentation: https://docs.stackstorm.com/
* Community: https://stackstorm.com/community-signup
* Forum: https://forum.stackstorm.com/
* Enterprise: https://stackstorm.com/#product Notice! It's recommended to use st2client container to work with StackStorm cluster.st2@938d4068b3ec:/opt/stackstorm$ cd /etc/ssh
st2@938d4068b3ec:/etc/ssh$ ls
moduli      sshd_config         ssh_host_ecdsa_key.pub  ssh_host_ed25519_key.pub  ssh_host_rsa_key.pub
ssh_config  ssh_host_ecdsa_key  ssh_host_ed25519_key    ssh_host_rsa_key          ssh_import_id

```

These are generated by the openssh-server  package installation as a dependency to st2.deb.
They are not used as you can't run SSH server in StackStorm Docker images and don't want these keys in there, pre-packaged and distributed Docker image is not a VM.

**Comment by armab** [comment]
Thanks for the report.
It's indeed a good find! We definitely don't want SSH server keys bundled in the Docker image.

We'll need to remove `ssh-server` from `deb`/`rpm` package dependencies and let users install the server if they want:
* https://github.com/StackStorm/st2-packages/blob/5d92c2514550b1cf7996f3f15f7ba56f9064da55/packages/st2/debian/control#L16
* https://github.com/StackStorm/st2-packages/blob/5d92c2514550b1cf7996f3f15f7ba56f9064da55/packages/st2/rpm/st2.spec#L18-L23

This is a good first issue, help wanted!

**Comment by ashm2** [comment]
Thanks @armab will submit a PR for this to remove them from the dockerfiles

**Comment by armab** [comment]
Sounds good! :+1:
