### ISSUE TITLE
CentOS7 packagingtest needs re-build

### ISSUE THREAD

**Issue by armab** [StackStorm/st2-dockerfiles#38]
It looks like old version of `stackstorm/packagingtest:centos7` Docker image which exists in [Docker Hub](https://hub.docker.com/r/stackstorm/packagingtest/tags/) was built/uploaded based on really outdated [`centos:7`](https://github.com/StackStorm/st2-dockerfiles/blob/01637be72714eba4cf6f8900c2dc67ff5a5b7bc3/packagingtest/centos7/systemd/Dockerfile#L1)

The problem with that outdated `centos:7` is that it has `/run/nologin` which blocks non-root ssh access.

See related Issues: 
- [`CentOS/sig-cloud-instance-images`: /var/run/nologin in centos:latest](https://github.com/CentOS/sig-cloud-instance-images/issues/60)
- [`docker-library/official-images`: update to fix incorrect /var/run/nologin file #1962](https://github.com/docker-library/official-images/pull/1962)
- https://ask.fedoraproject.org/en/question/40288/ssh-in-fedora-20-fails-with-error-system-is-booting-up/
- https://bugzilla.redhat.com/show_bug.cgi?id=1043212

cc @Mierdin the problem you hit in https://github.com/StackStorm/ansible-st2/pull/71

**Comment by Mierdin** [comment]
@armab nice fix - looks like its a bad systemd configuration/install based on [this](https://bugzilla.redhat.com/show_bug.cgi?id=1043212)

**Comment by armab** [comment]
Fixed in https://github.com/StackStorm/st2-dockerfiles/pull/43 and updated `ansible-st2` Dockerfiles https://github.com/StackStorm/ansible-st2/pull/115
