### ISSUE TITLE
Add New user on stackstom

### ISSUE THREAD

**Issue by dwedaz** [StackStorm/st2-dockerfiles#50]
how to add stack storm user?  

https://docs.stackstorm.com/rbac.html#user-creation

i am trying to enter in container (docker exec -it stackstorm /bin/bash) then adduser admin then passwd admin  but nothing happen.

**Comment by armab** [comment]
Hi, thanks for trying `st2-dockerfiles`.

This repo is outdated and will be deprecated as Dockerized StackStorm.
Please use the https://github.com/StackStorm/st2-docker instead which is now official StackStorm Docker.

Please try it there and feel free to open an issue if something went wrong.
Additionally, we have Slack community https://stackstorm.typeform.com/to/K76GRP with dedicated #docker channel.
