### ISSUE TITLE
st2chatops dockerfile readme incomplete

### ISSUE THREAD

**Issue by MrDiba** [StackStorm/st2-dockerfiles#51]
As it is required to enable st2chatops by setting the environment variable `ST2_CHATOPS_ENABLE` before using the container, this should be added to the readme as a required variable.

**Comment by armab** [comment]
Thanks for the report!

I think it's documented here already: https://github.com/stackStorm/st2-docker#compose-configuration

Just setting the ENV variable in this repository won't have effect as the configuration is relevant to docker-compose repository above and not container specific.

Hope that helps.

**Comment by MrDiba** [comment]
Ah okay, I understand! Thank you for the explanation.
