### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by chain312** [StackStorm/st2-dockerfiles#56]
## Problem description
I use git clone code to go locally, and I get the following error with `make build`
`[root@node-01 st2-dockerfiles-master]# make build
Failed to identify the tags to be set.
No images were tagged due to an error when determining the correct tags: Error: Unexpected HTTP statuscode for https://registry.hub.docker.com
exit 1
make: *** [verify_tag_update_flag] 错误 1`
![image](https://user-images.githubusercontent.com/30886624/192707877-55c412aa-7797-499c-839d-fef3353f0294.png)
I got the same error when I visited [https://registry.hub.docker.com/v1/repositories/stackstorm/st2/tags ](https://registry.hub.docker.com/v1/repositories/stackstorm/st2/tags) directly.
![image](https://user-images.githubusercontent.com/30886624/192708261-808a576c-4b16-40cf-88dd-53917e263680.png)

**Comment by armab** [comment]
Fixed in https://github.com/StackStorm/st2-dockerfiles/pull/58
