### ISSUE TITLE
No images available for release v3.8.0

### ISSUE THREAD

**Issue by rite2hhh** [StackStorm/st2-dockerfiles#57]
Spot checked a few of these images on https://hub.docker.com/u/stackstorm and didn't find a release tag for v3.8.0.

Example from the st2web image tags section:

The most recent release tag was `3.7.0`. Following dev images available:

- 3.8dev
- 3.9dev 

Also looks like `latest` was published 7 mo ago (probably at v3.7.0)

![image](https://user-images.githubusercontent.com/29960411/204680371-3ec80e4b-29d6-47f3-bd55-1ea9f65dd287.png)

**Comment by armab** [comment]
Thanks for reporting.
Per https://app.circleci.com/pipelines/github/StackStorm/st2-dockerfiles/1171/workflows/f788c9e4-ee29-47a6-8546-ef87e8f8272a/jobs/1704 looks like the build failed for the v3.8 branch:

```
#!/bin/sh -eo pipefail
make build

Failed to identify the tags to be set.
No images were tagged due to an error when determining the correct tags: Error: Unexpected HTTP statuscode for https://registry.hub.docker.com/v1/repositories/stackstorm/st2/tags: 410
exit 1
make: *** [Makefile:101: verify_tag_update_flag] Error 1

Exited with code exit status 2


```

**Comment by armab** [comment]
Confirming the images are on the Docker Hub now.
Thanks again for reporting this @rite2hhh .
